object Versions {
    const val KOTLIN = "1.7.10"
    const val NAVIGATION = "2.3.5"
    const val COROUTINES = "1.5.0"
    const val APPCOMPAT = "1.4.0"
    const val ANDROID_CORE_KTX = "1.3.2"
    const val CONSTRAINT_LAYOUT = "2.2.0-alpha01"
    const val CARD_VIEW = "1.0.0"
    const val LIFECYCLE_KTX = "2.4.0"
    const val RECYCLERVIEW = "1.2.1"
    const val MATERIAL = "1.4.0"
    const val TIMBER_KT = "1.5.1"
    const val DAGGER = "2.36"
    const val SHIMMER_JETPACK_COMPOSE = "1.0.3"
    const val GRADLE_VERSION_PLUGIN = "0.36.0"
    const val FRAGMENT_KTX = "1.3.4"
    const val COMPOSE_ACTIVITY = "1.3.1"
    const val COMPOSE = "1.2.1"
    const val COMPOSE_COMPILER = "1.3.1"
    const val COMPOSE_MATERIAL = "1.0.0-beta03"
    const val COMPOSE_LIFECYCLE = "1.0.0-alpha07"
    const val ANDROID_LIB = "7.3.0"
}
